default_platform(:android)

platform :android do
  desc "Lane for Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:286002132683:android:d87c6853cafe78ddd58d4e",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "magddevf@gmail.com",
    upload_timeout: 600,
    release_notes: "Fastlane first test release"
  )
  end
end
